import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "EAIN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  isHomePage,
}: Readonly<{
  children: React.ReactNode;
  isHomePage?: boolean; // Add this line to define isHomePage property
}>) {
  return (
    <html lang="en">
      <body>
        {!isHomePage && <Navbar />}
        <main className="relative overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

